### ISSUE TITLE
Why no Charts.js/angles.js?

### ISSUE THREAD

**Issue by earcanal** [saurabhgupta050890/ionic-chart-example#2]
I'm curious as to why the Charts.js/angles.js example is commented out.  I'm using this repo to test various libs on android and that was the specific combination I've found problematic!  FWIW when I enabled the angles.js chart I got the follow results:

| Library | Chrome rendering | Android rendering |
| --- | --- | --- |
| NVD3 JS | :white_check_mark: | :white_check_mark: |
| HighCharts | :white_check_mark: | :white_check_mark: |
| Google chart | :white_check_mark: | :white_check_mark: |
| Chart.js/angles.js | :white_check_mark: | :x: |

**Comment by saurabhgupta050890** [comment]
Yup .. you are right. When I created this sample Chart/Angles was the first lib I tried. We were using ChartJS in our Web application so that was the first choice. I had issues with ChartJS specifically related to responsiveness (When tried on tablet screens). Also for some Android devices (Micromax) there were rendering problems , so I dropped that code. 
I was hoping by now it might be working. Anyways please share your test results
